1. クラス間の関係
----------------------------------------
@startuml class.1_relation1
Class01 <|-- Class02 
Class03 *-- Class04 
Class05 o-- Class06 
Class07 .. Class08 
Class09 -- Class10
@enduml

@startuml class.1_relation2
Class11 <|.. Class12 
Class13 --> Class14 
Class15 ..> Class16 
Class17 ..|> Class18 
Class19 <--* Class20
@enduml

@startuml class.1_relation3
Class21 #-- Class22 
Class23 x-- Class24 
Class25 }-- Class26 
Class27 +-- Class28 
Class29 ^-- Class30 
@enduml


2. 関係ラベル
----------------------------------------
@startuml class.2_label1
Class01 "1" *-- "many" Class02 : contains
Class03 o-- Class04 : aggregation
Class05 --> "1" Class06
@enduml

@startuml class.2_label2
class Car
Driver - Car : drives > 
Car *- Wheel : have 4 > 
Car -- Person : < owns
@enduml


3. メンバー
----------------------------------------
@startuml class.3_member1
Object <|-- ArrayList
Object : equals() 
ArrayList : Object[] elementData 
ArrayList : size()
@enduml

@startuml class.3_member2
class Dummy { 
    String data 
    void methods() 
}
class Flight { 
    flightNumber : Integer 
    departureTime : Date 
} 
@enduml

@startuml class.3_member3
class Dummy {
    {field} A field (despite parentheses) 
    {method} Some method 
}
@enduml


4. 可視性
----------------------------------------
@startuml class.4_accessibility1
class Dummy {
     -field1 
     #field2 
     ~method1() 
     +method2() 
}
@enduml

@startuml class.4_accessibility2
skinparam classAttributeIconSize 0 
class Dummy { 
    -field1 
    #field2 
    ~method1() 
    +method2() 
}
@enduml


5. メンバー修飾
----------------------------------------
@startuml class.5_classmodifier
class Dummy {
     {static} String id 
     {abstract} void methods()
}
@enduml


6. セパレーター
----------------------------------------
@startuml class.6_separator
class Foo1 { 
You can use 
several lines 
..
as you want 
and group 
==
things together.
__
You can have as many groups 
as you want 
--
End of class
}
class User { 
.. Simple Getter ..
+ getName() 
+ getAddress() 
.. Some setter ..
+ setName() 
__ private data __
int age 
-- encrypted --
String password 
}
@enduml


7. 注釈とステレオタイプ
----------------------------------------
@startuml class.7_note_stereotype
class Object << general >> 
Object <|--- ArrayList

note top of Object : In java, every class\nextends this one.

note "This is a floating note" as N1 
note "This note is connected\nto several objects." as N2 
Object .. N2 
N2 .. ArrayList

class Foo 
note left: On last defined class
@enduml

@startuml class.7_linknote
class Dummy 
Dummy --> Foo : A link 
note on link #red: note that is red

Dummy --> Foo2 : Another link
note right on link #blue
this is my note on right link
and in blue
end note
@enduml


8. 抽象クラスとインタフェース
----------------------------------------
@startuml class.8_abstract_interface
abstract class AbstractList 
abstract AbstractCollection 
interface List
interface Collection

List <|-- AbstractList 
Collection <|-- AbstractCollection

Collection <|- List 
AbstractCollection <|- AbstractList 
AbstractList <|-- ArrayList

class ArrayList { 
    Object[] elementData 
    size() 
}
enum TimeUnit { 
    DAYS 
    HOURS 
    MINUTES 
}
annotation SuppressWarnings
@enduml


9. ジェネリック
----------------------------------------
@startuml class.9_generic
class Foo<? extends Element> { 
    int size() 
} 
Foo *- Element
@enduml


10. カスタムアイコン
----------------------------------------
@startuml class.10_customicon
class System << (S,#FF7700) Singleton >> 
class Date << (D,orchid) >> 
@enduml


11. パッケージ1
----------------------------------------
@startuml class.11_package1
package "Classic Collections" #DDDDDD { 
Object <|-- ArrayList
}
package net.sourceforge.plantuml { 
Object <|-- Demo1 
Demo1 *- Demo2 
}
@enduml

@startuml class.11_package2
scale 750 width 
package foo1 <<Node>> { 
class Class1 
}
package foo2 <<Rectangle>> { 
class Class2
}
package foo3 <<Folder>> { 
class Class3 
}
package foo4 <<Frame>> { 
class Class4
}
package foo5 <<Cloud>> { 
class Class5
}
package foo6 <<Database>> { 
class Class6
}
@enduml

@startuml class.11_package3
skinparam packageStyle rectangle
package foo1.foo2 {
}
package foo1.foo2.foo3 { 
class Object 
}
foo1.foo2 +-- foo1.foo2.foo3
@enduml


12. 名前空間
----------------------------------------
@startuml class.12_namespace
class BaseClass
namespace net.dummy #DDDDDD { 
.BaseClass <|-- Person 
Meeting o-- Person
.BaseClass <|- Meeting
}
namespace net.foo { 
net.dummy.Person <|- Person 
.BaseClass <|-- Person
net.dummy.Meeting o-- Person
}
BaseClass <|-- net.unused.Person
@enduml

@startuml class.12_namespace2
set namespaceSeparator :: 
class X1::X2::foo { 
some info
}
@enduml

@startuml class.12_namespace3
set namespaceSeparator none 
class X1.X2.foo { 
some info 
}
@enduml


13. ロリポップ
----------------------------------------
@startuml class.13_lollipop
class foo 
bar ()- foo 
@enduml


14. 配置
----------------------------------------
@startuml class.14_location1
Room o- Student 
Room *-- Chair 
@enduml

@startuml class.14_location2
Student -o Room 
Chair --* Room 
@enduml

@startuml class.14_location3
foo -left-> dummyLeft 
foo -right-> dummyRight 
foo -up-> dummyUp 
foo -down-> dummyDown 
@enduml


15. 関連クラス
----------------------------------------
@startuml class.15_relatedclass1
class Student { 
Name
} 
Student "0..*" - "1..*" Course 
(Student, Course) .. Enrollment
class Enrollment { 
drop() 
cancel() 
} 
@enduml

@startuml class.15_relatedclass2
class Student { 
Name 
} 
Student "0..*" -- "1..*" Course 
(Student, Course) . Enrollment
class Enrollment { 
drop() 
cancel() 
} 
@enduml

16. スキンパラメータ
----------------------------------------
@startuml class.16_skin1
skinparam class { 
BackgroundColor PaleGreen 
ArrowColor SeaGreen 
BorderColor SpringGreen 
} 
skinparam stereotypeCBackgroundColor YellowGreen
Class01 "1" *-- "many" Class02 : contains
Class03 o-- Class04 : aggregation
@enduml

@startuml class.16_skin2
skinparam class { 
BackgroundColor PaleGreen 
ArrowColor SeaGreen 
BorderColor SpringGreen 
BackgroundColor<<Foo>> Wheat 
BorderColor<<Foo>> Tomato 
} 
skinparam stereotypeCBackgroundColor YellowGreen 
skinparam stereotypeCBackgroundColor<< Foo >> DimGray
Class01 <<Foo>> 
Class03 <<Foo>> 
Class01 "1" *-- "many" Class02 : contains
Class03 o-- Class04 : aggregation
@enduml

@startuml class.16_skin3
skinparam backgroundcolor AntiqueWhite/Gold 
skinparam classBackgroundColor Wheat|CornflowerBlue
class Foo #red-green 
note left of Foo #blue\9932CC 
this is my 
note on this class 
end note
package example #GreenYellow/LightGoldenRodYellow { 
class Dummy 
}
@enduml


17. レイアウト
----------------------------------------
@startuml class.17_layout
class Bar1 
class Bar2 
together { 
class Together1 
class Together2 
class Together3 
} 
Together1 - Together2 
Together2 - Together3 
Together2 -[hidden]--> Bar1 
Bar1 -[hidden]> Bar2
@enduml


18. 分割
----------------------------------------
@startuml class.18_split
' Split into 4 pages 
page 2x2
skinparam pageMargin 10 
skinparam pageExternalColor gray 
skinparam pageBorderColor black
class BaseClass
namespace net.dummy #DDDDDD { 
.BaseClass <|-- Person 
Meeting o-- Person
.BaseClass <|- Meeting
}
namespace net.foo { 
net.dummy.Person <|- Person 
.BaseClass <|-- Person
net.dummy.Meeting o-- Person 
}
BaseClass <|-- net.unused.Person 
@enduml
