1. 基本
@startuml state.1_basic

[*] --> State1 
State1 --> [*] 
State1 : this is a string 
State1 : this is another string

State1 -> State2 
State2 --> [*]

@enduml

2. 複合状態
@startuml state.2_composition
scale 350 width 
[*] --> NotShooting

state NotShooting { 
[*] --> Idle 
Idle --> Configuring : EvConfig 
Configuring --> Idle : EvConfig 
}

state Configuring { 
[*] --> NewValueSelection 
NewValueSelection --> NewValuePreview : EvNewValue 
NewValuePreview --> NewValueSelection : EvNewValueRejected 
NewValuePreview --> NewValueSelection : EvNewValueSaved

state NewValuePreview { 
State1 -> State2
}

}
@enduml

3. 領域
@startuml state.3_region
[*] --> Active
state Active { 
[*] -> NumLockOff 
NumLockOff --> NumLockOn : EvNumLockPressed 
NumLockOn --> NumLockOff : EvNumLockPressed
--
[*] -> CapsLockOff 
CapsLockOff --> CapsLockOn : EvCapsLockPressed 
CapsLockOn --> CapsLockOff : EvCapsLockPressed 
--
[*] -> ScrollLockOff 
ScrollLockOff --> ScrollLockOn : EvCapsLockPressed 
ScrollLockOn --> ScrollLockOff : EvCapsLockPressed 
}
@enduml

4. 矢印の向き
@startuml state.4_arrow
[*] -up-> First 
First -right-> Second 
Second ---> Third 
Third -left-> Last
@enduml

5. 注釈
@startuml state.5_note
[*] --> Active 
Active --> Inactive

note left of Active : this is a short\nnote

note right of Inactive 
A note can also 
be defined on 
several lines 
end note
@enduml

6. スキン
@startuml state.6_skin

skinparam backgroundColor LightYellow 
skinparam state { 
StartColor MediumBlue 
EndColor Red 
BackgroundColor Peru 
BackgroundColor<<Warning>> Olive 
BorderColor Gray 
FontName Impact 
}

[*] --> NotShooting

state "Not Shooting State" as NotShooting {
state "Idle mode" as Idle <<Warning>> 
state "Configuring mode" as Configuring 
[*] --> Idle 
Idle --> Configuring : EvConfig 
Configuring --> Idle : EvConfig 
}

NotShooting --> [*] 
@enduml

@startuml uml_statechart
state "状態1" as state1
state "状態2" as state2

state1: entry / 入場アクション
state1: do / アクティビティ
state1: exit / 退場アクション
state1: イベント / アクション

[*] --> state1
state1 -> state2 : イベント[ガード条件] / アクション
state1 --> [*]
@enduml
